

INSERT INTO `gestion_factoria`.`thge030_area` 
VALUES 
(1, 'FABRICA DE PRUEBAS'), 
(2, 'FABRICA DE SOFTWARE');

INSERT INTO `gestion_factoria`.`thge002_tecnologia`  
VALUES 
(1, '.NET'),
(2, 'ADAEVOS'),
(3, 'BI'),
(4, 'ESSBASE'),
(5, 'HOST'),
(6, 'JAVA'),
(7, 'MICROSTRATEGY'),
(8, 'NACAR'),
(9, 'ORACLE'),
(10, 'POWER BUILDER'),
(11, 'POWER CENTER'),
(12, 'PRUEBAS'),
(13, 'SCRUM'),
(14, 'SPRING'),
(15, 'VISUAL BASIC');

-- BANCA
INSERT INTO `gestion_factoria`.`THGE034_BANCA`  
VALUES 
(1 , 'BANCA DE EMPRESAS'),
(2 , 'COMUNICACIÓN Y RELACIONES INSTITUCIONALE'),
(3 , 'CONSOLIDADO RECURSOS HUMANOS'),
(4 , 'CONSOLIDADO SERVICIOS JURÍDICOS'),
(5 , 'CONSOLIDADO SISTEMAS Y OPERACIÓN'),
(6 , 'CORPORATE & INVESTEMENT BANKING'),
(7 , 'DESARROLLO DE NEGOCIO Y MEDIOS DE PAGO'),
(8 , 'DIR. GENERAL DE MERCADOS'),
(9 , 'FINANZAS Y CONTRALORIA'),
(10 , 'RED + OTRAS ÁREAS BANCA COMERCIAL'),
(11 , 'RIESGOS'),
(12 , 'TRANSFORMACIÓN CALIDAD Y DES. CORP.'),
(13 , 'TRANSFORMACION DIGITAL');

-- METODOLOGIA
-- INSERT INTO `gestion_factoria`.`TABLE_NAME`  
-- VALUES 
-- (1, 'SCRUM'),
-- (2, 'WATERFALL');

-- TIPO DE SERVICIO
INSERT INTO `gestion_factoria`.`thge001_tipo_serv`  
VALUES 
(1 , 'PRUEBAS FUNCIONALES'),
(2 , 'EJECUCIÓN DE CASOS DE PRUEBA'),
(3 , 'PRUEBAS DE NO AFECTACIÓN'),
(4 , 'PRUEBAS DE ACEPTACIÓN'),
(5 , 'PRUEBAS DE USUARIO'),
(6 , 'SERVICIO DE AMBIENTACIÓN'),
(7 , 'PROCESOS BATCH'),
(8 , 'PRUEBAS FUNCIONALES Y NO AFECTACIÓN');

-- PRODUCTO
INSERT INTO `gestion_factoria`.`thge018_producto`
VALUES 
('J01',	'PANTALLA ESTÁTICA', 6),
('J02',	'PANTALLA DINÁMICA', 6),
('J03',	'PLANTILLA', 6),
('J04',	'FICHERO CONGIRUACIÓN', 6),
('J05',	'CLASE', 6),
('J06',	'MÉTODO', 6),
('J07',	'PROCEDIMIENTOS ALMACENADOS', 6),
('J08',	'SCRIPTS', 6),
('J09',	'JAVASCRIPTS REUTILIZABLES', 6),
('HA1',	'ESQUELETO CÓDIGO AUTOMÁTICO', 5),
('HB1',	'LISTADO', 5),
('HB2',	'CRUCE DE FICHEROS', 5),
('HB3',	'VALID. Y FORM. SALIDA/EXTRACTOR', 5),
('HB4',	'ACTUAL. DB2 BATCH', 5),
('HC1',	'COPY,FORMULARIO O FORMATO (E/S)', 5),
('HJ1',	'JCL/PROCLIB/CTC/PARMLIB', 5),
('HM1',	'MAPA 3270', 5),
('HO1',	'SERV. DIRECTOR', 5),
('HO2',	'SERV. CONSULTA', 5),
('HO3',	'SERV. LISTA', 5),
('HO4',	'SERV. MANTENIMIENTO', 5),
('HR1',	'RUTINA CONSULTA', 5),
('HR2',	'RUTINA MANTENIMIENTO', 5),
('HR3',	'RUTINA LISTA', 5),
('N01',	'FLUJO', 8),
('N02',	'VENTANA', 8),
('N03',	'RUTINAS DE NEGOCIO', 8),
('N04',	'JAVASCRIPTS REUTILIZABLES', 8),
('N05',	'PROCEDIMIENTOS ALMACENADOS', 8),
('N06',	'SERVICIOS DE DATOS', 8),
('N07',	'PLANTILLAS XSL - FO ESTÁTICAS', 8),
('N08',	'FLUJOS AUTOMATICOS', 8);
